# python3 spatiotemporal_transformer_nbody_gravity.py --optuna True --tensorboard True
# Equivariance
python3 spatiotemporal_transformer_nbody_gravity.py --tensorboard True --lr 6.062548606697973e-5 --batch_size 100 --weight_decay 0 --n_egnn_layers 3 --n_stacking_layers 2 --hidden_nf 64 --spatial_attention True --temporal_attention True --positional_encoding True --causal_attention True --dropout 0.5 --kappa 100000 --equivariant True --adjacency True --recurrent True --optuna False --dataset nbody_gravity_5 --num_atoms 5 --spatial_model_type egnnvelschnet
python3 spatiotemporal_transformer_nbody_gravity.py --tensorboard True --lr 6.062548606697973e-5 --batch_size 100 --weight_decay 0 --n_egnn_layers 3 --n_stacking_layers 2 --hidden_nf 64 --spatial_attention True --temporal_attention True --positional_encoding True --causal_attention True --dropout 0.5 --kappa 100000 --equivariant False --adjacency True --recurrent True --optuna False --dataset nbody_gravity_5 --num_atoms 5 --spatial_model_type egnnvelschnet

# Adjacency
python3 spatiotemporal_transformer_nbody_gravity.py --tensorboard True --lr 6.062548606697973e-5 --batch_size 100 --weight_decay 0 --n_egnn_layers 3 --n_stacking_layers 2 --hidden_nf 64 --spatial_attention True --temporal_attention True --positional_encoding True --causal_attention True --dropout 0.5 --kappa 100000 --equivariant True --adjacency True --recurrent True --optuna False --dataset nbody_gravity_5 --num_atoms 5 --spatial_model_type egnnvelschnet
python3 spatiotemporal_transformer_nbody_gravity.py --tensorboard True --lr 6.062548606697973e-5 --batch_size 100 --weight_decay 0 --n_egnn_layers 3 --n_stacking_layers 2 --hidden_nf 64 --spatial_attention True --temporal_attention True --positional_encoding True --causal_attention True --dropout 0.5 --kappa 100000 --equivariant True --adjacency False --recurrent True --optuna False --dataset nbody_gravity_5 --num_atoms 5 --spatial_model_type egnnvelschnet

# Attention
python3 spatiotemporal_transformer_nbody_gravity.py --tensorboard True --lr 6.062548606697973e-5 --batch_size 100 --weight_decay 0 --n_egnn_layers 3 --n_stacking_layers 2 --hidden_nf 64 --spatial_attention True --temporal_attention True --positional_encoding True --causal_attention True --dropout 0.5 --kappa 100000 --equivariant True --adjacency True --recurrent True --optuna False --dataset nbody_gravity_5 --num_atoms 5 --spatial_model_type egnnvelschnet
python3 spatiotemporal_transformer_nbody_gravity.py --tensorboard True --lr 6.062548606697973e-5 --batch_size 100 --weight_decay 0 --n_egnn_layers 3 --n_stacking_layers 2 --hidden_nf 64 --spatial_attention True --temporal_attention False --positional_encoding True --causal_attention True --dropout 0.5 --kappa 100000 --equivariant True --adjacency True --recurrent True --optuna False --dataset nbody_gravity_5 --num_atoms 5 --spatial_model_type egnnvelschnet
